service: api

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

  environment:
    DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}

functions:
  register:
    role: ${ssm:${self:custom.stage}-users-register-iam-role}
    handler: register/handler.register
    events:
      - http:
          path: users
          method: post
    environment:
      SNS_USERS_NOTIFICATIONS_TOPIC: ${ssm:${self:custom.stage}-users-register-notifications-topic}

custom:
  stage: ${opt:stage, self:provider.stage}